### ISSUE TITLE
膜一波

### ISSUE THREAD

**Issue by YuYanDev** [eczn/Rally#1]
大佬是如何在gitpage里搞定history路由的，还是是类似hexo那种生成器呀？

还在用hash路由的我，卑微。

**Comment by eczn** [comment]
写个koa server
把收到的请求对应的path通过react-router里的static router的方式指定页面router进行服务端渲染

渲染后，通过读取服务端渲染结果中的a标签找到下一个链接，递归地过一次广度优先图遍历。

最后，就可以生成静态内容了。

大体如此，不过有些细节建议你clone下来看看代码了

**Comment by YuYanDev** [comment]
> 写个koa server
> 把收到的请求对应的path通过react-router里的static router的方式指定页面router进行服务端渲染
> 
> 渲染后，通过读取服务端渲染结果中的a标签找到下一个链接，递归地过一次广度优先图遍历。
> 
> 最后，就可以生成静态内容了。
> 
> 大体如此，不过有些细节建议你clone下来看看代码了

明白了，感谢
